// <auto-generated />
using Api1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Api1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210322130154_default_data")]
    partial class default_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Api1.Entities.Catalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 1000,
                            Title = "Catalog 1"
                        },
                        new
                        {
                            Id = 2,
                            Price = 2000,
                            Title = "Catalog 2"
                        },
                        new
                        {
                            Id = 3,
                            Price = 3000,
                            Title = "Catalog 3"
                        },
                        new
                        {
                            Id = 4,
                            Price = 4000,
                            Title = "Catalog 4"
                        },
                        new
                        {
                            Id = 5,
                            Price = 5000,
                            Title = "Catalog 5"
                        },
                        new
                        {
                            Id = 6,
                            Price = 6000,
                            Title = "Catalog 6"
                        },
                        new
                        {
                            Id = 7,
                            Price = 7000,
                            Title = "Catalog 7"
                        },
                        new
                        {
                            Id = 8,
                            Price = 8000,
                            Title = "Catalog 8"
                        },
                        new
                        {
                            Id = 9,
                            Price = 9000,
                            Title = "Catalog 9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
